"""initial schema

Revision ID: 0343930ce53d
Revises: 
Create Date: 2026-01-24 22:26:45.282128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0343930ce53d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('poster', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_imdb_id'), 'movie', ['imdb_id'], unique=True)
    op.create_table('request_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(length=250), nullable=False),
    sa.Column('qquery_params', sa.Text(), nullable=True),
    sa.Column('result_status', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_log')
    op.drop_index(op.f('ix_movie_imdb_id'), table_name='movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
