"""Fix typo qquery_params to query_params

Revision ID: bedbe19c0a24
Revises: 0343930ce53d
Create Date: 2026-01-25 19:55:15.470300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bedbe19c0a24'
down_revision: Union[str, Sequence[str], None] = '0343930ce53d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_log', 'qquery_params', new_column_name='query_params')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_log', 'query_params', new_column_name='qquery_params')
    # ### end Alembic commands ###
